spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/myxiyifen/config-repo.git
          username: myxiyifen
          password: zfs147369258
  rabbitmq:
    addresses: 192.168.110.110
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"

#spring:
#  application:
#    name: config
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/myxiyifen/config-repo.git
##          username: 1017665216@qq.com
#          password: zfs147369258
#          username: myxiyifen
##    bus:
##      enabled: true
##      trace:
##        enabled: true
#  rabbitmq:
#    addresses: 192.168.110.110:5672
##    host: 192.168.110.110
##    port: 5672
##    username: guest
##    password: guest
##          设置配置文件存放目录
##          basedir: xxxxxxxxx
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
##management:
##  endpoints:
##    web:
##      expose: "*"
##management:
##  endpoints:
##    web:
##      expose: "*"
